services:
  postgres:
    image: postgres:latest
    container_name: my_postgres2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: jamil
      POSTGRES_PASSWORD: jamil123
      POSTGRES_DB: chatapp
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: my_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:81"

#  zookeeper:
#    image: confluentinc/cp-zookeeper:latest
#    container_name: zookeeper
#    ports:
#      - "2181:2181"
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#      ZOOKEEPER_TICK_TIME: 2000

#  kafka:
#    image: confluentinc/cp-kafka:latest
#    container_name: kafka
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_BROKER_ID: 1
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
##      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
##      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://host.docker.internal:9092
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

#  kafdrop:
#    image: obsidiandynamics/kafdrop
#    container_name: kafdrop
#    ports:
#      - "9000:9000"
#    environment:
#      KAFKA_BROKERCONNECT: "192.168.1.5:9092"
#      JVM_OPTS: "-Xms32M -Xmx64M"
#    networks:
#      - kafka-net
#
#networks:
#  kafka-net:
#    external: true

volumes:
  postgres_data:



